FROM balenalib/%%BALENA_MACHINE_NAME%%:buster

ENV DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket

# Install shairport-sync
RUN install_packages shairport-sync

COPY start.sh /usr/src/

# Start app
CMD [ "bash", "/usr/src/start.sh" ]
