version: '2'
services:
  wifi-connect:
    build: ./wifi-connect
    restart: always
    network_mode: host
    privileged: true
    labels:
      io.balena.features.dbus: '1'
      io.balena.features.firmware: '1'
  airpod:
    build: ./airpod
    restart: always
    network_mode: host
    privileged: true
    labels:
      io.balena.features.dbus: 1